"""Type stubs for networkx library."""

from typing import Any

class Graph:
    def __init__(self, **kwargs: Any) -> None: ...
    def add_node(self, node: Any, **kwargs: Any) -> None: ...
    def add_edge(self, u: Any, v: Any, **kwargs: Any) -> None: ...
    def nodes(self) -> list[Any]: ...
    def edges(self) -> list[tuple[Any, Any]]: ...
    def degree(self, node: Any) -> int: ...
    def neighbors(self, node: Any) -> list[Any]: ...

class DiGraph(Graph): ...
