services:
  alertmanager:
    image: prom/alertmanager:latest
    ports:
    - 9093:9093
    volumes:
    - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    - alertmanager_data:/alertmanager
  grafana:
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    image: grafana/grafana:latest
    ports:
    - 3000:3000
    volumes:
    - grafana_data:/var/lib/grafana
    - ./dashboards:/var/lib/grafana/dashboards
  prometheus:
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    - --storage.tsdb.path=/prometheus
    - --web.console.libraries=/etc/prometheus/console_libraries
    - --web.console.templates=/etc/prometheus/consoles
    - --web.enable-lifecycle
    image: prom/prometheus:latest
    ports:
    - 9090:9090
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    - ./alert_rules.yml:/etc/prometheus/alert_rules.yml
    - prometheus_data:/prometheus
version: '3.8'
volumes:
  alertmanager_data: {}
  grafana_data: {}
  prometheus_data: {}
