alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093
global:
  evaluation_interval: 15s
  scrape_interval: 15s
rule_files: []
scrape_configs:
- job_name: discord-bot
  metrics_path: /metrics
  scrape_interval: 15s
  static_configs:
  - targets:
    - localhost:8000
