---
process_video:
  description: >-
    Use the pipeline tool to download {url}, transcribe and analyse the audio,
    then post the summary and Drive links to Discord.
  expected_output: Summary of the processed video posted to Discord.
  agent: content_manager

execute_multi_platform_downloads:
  description: >-
    Retrieve media from a list of URLs spanning YouTube, Twitch, Kick and
    Twitter. Return metadata for each successful download.
  expected_output: Local file paths and metadata for downloaded media.
  agent: content_downloader

monitor_system:
  description: >-
    Post an alert to the private Discord channel with the provided message.
  expected_output: Confirmation that the alert was posted.
  agent: system_alert_manager
