# Active Tasks (Implemented in crew.py)
#
# These tasks correspond to @task methods in crew.py and are actively used
# by the CrewAI system. Additional planned tasks are in future_tasks.yaml.
#
# Core workflow tasks for autonomous intelligence processing

plan_autonomy_mission:
  description: >-
    Launch or resume the end-to-end intelligence mission for {request}. Sequence
    acquisition, transcription, analysis, verification, and memory stages using the
    pipeline tool while tracking budgets and documenting key decisions.
  expected_output: Mission run log including staged plan, tool usage, and final routing instructions.
  agent: mission_orchestrator
  human_input: false
  async_execution: false
  output_file: output/mission_plan_{timestamp}.md

capture_source_media:
  description: >-
    Resolve and download the highest-quality media for {url} across all supported
    platforms, capturing rich metadata and uploading artefacts when size limits are hit.
  expected_output: Download manifest containing file paths, formats, durations, and resolver notes.
  agent: acquisition_specialist
  human_input: false
  async_execution: false
  output_file: output/download_manifest_{url_hash}.json

transcribe_and_index_media:
  description: >-
    Produce accurate transcripts, searchable indices, and aligned timelines for the
    captured media package.
  expected_output: Transcript bundle with timestamps, quality indicators, and index references.
  agent: transcription_engineer
  context:
    - capture_source_media
  human_input: false
  async_execution: false
  output_file: output/transcript_{url_hash}.json

map_transcript_insights:
  description: >-
    Analyse transcripts for sentiment shifts, topical clusters, and noteworthy excerpts
    that downstream teams must review.
  expected_output: Structured insight report containing themes, sentiment summary, and highlighted excerpts.
  agent: analysis_cartographer
  context:
    - transcribe_and_index_media
  human_input: false
  async_execution: false
  output_file: output/insight_map_{url_hash}.json

verify_priority_claims:
  description: >-
    Extract and fact-check consequential claims from the analysed content, capturing
    verdicts, confidence levels, and supporting evidence.
  expected_output: Verification dossier with claim list, verdicts, fallacy notes, and citations.
  agent: verification_director
  context:
    - map_transcript_insights
  human_input: false
  async_execution: false
  output_file: output/verification_{url_hash}.json
