"""Minimal type stubs for PyTorch."""

from typing import Any

class Tensor: ...
class dtype: ...
class device: ...

def tensor(data: Any, dtype: dtype | None = None, device: device | None = None) -> Tensor: ...
def load(f: Any, map_location: Any = None) -> Any: ...

cuda: Any
