# Content Type Definitions and Routing Configuration
# This file defines content types, their characteristics, and routing rules

content_types:
  # Video Content Types
  video:
    youtube:
      type: "video"
      platform: "youtube"
      characteristics:
        - "long_form"
        - "educational"
        - "entertainment"
        - "live_streaming"
      processing_requirements:
        - "transcription"
        - "visual_analysis"
        - "audio_analysis"
      quality_thresholds:
        min_duration: 30  # seconds
        max_duration: 14400  # 4 hours
        min_quality: 720  # pixels
      routing_rules:
        analysis_agent: "analysis_specialist"
        verification_agent: "verification_specialist"
        quality_agent: "quality_assurance_specialist"
    
    tiktok:
      type: "video"
      platform: "tiktok"
      characteristics:
        - "short_form"
        - "viral_potential"
        - "trending"
        - "mobile_optimized"
      processing_requirements:
        - "quick_analysis"
        - "trend_detection"
        - "viral_scoring"
      quality_thresholds:
        min_duration: 3  # seconds
        max_duration: 180  # 3 minutes
        min_quality: 480  # pixels
      routing_rules:
        analysis_agent: "enhanced_social_media_archivist"
        verification_agent: "advanced_verification_specialist"
        quality_agent: "quality_assurance_specialist"
    
    twitch:
      type: "video"
      platform: "twitch"
      characteristics:
        - "live_streaming"
        - "interactive"
        - "gaming_focused"
        - "community_driven"
      processing_requirements:
        - "real_time_analysis"
        - "chat_analysis"
        - "stream_quality_assessment"
      quality_thresholds:
        min_duration: 60  # seconds
        max_duration: 28800  # 8 hours
        min_quality: 720  # pixels
      routing_rules:
        analysis_agent: "live_stream_analysis_specialist"
        verification_agent: "verification_specialist"
        quality_agent: "quality_assurance_specialist"
    
    instagram:
      type: "video"
      platform: "instagram"
      characteristics:
        - "visual_focused"
        - "story_format"
        - "reels_support"
        - "ephemeral_content"
      processing_requirements:
        - "visual_analysis"
        - "story_archiving"
        - "engagement_analysis"
      quality_thresholds:
        min_duration: 1  # seconds
        max_duration: 60  # 1 minute
        min_quality: 480  # pixels
      routing_rules:
        analysis_agent: "enhanced_social_media_archivist"
        verification_agent: "advanced_verification_specialist"
        quality_agent: "quality_assurance_specialist"

  # Audio Content Types
  audio:
    podcast:
      type: "audio"
      platform: "podcast"
      characteristics:
        - "long_form"
        - "conversational"
        - "educational"
        - "serialized"
      processing_requirements:
        - "transcription"
        - "speaker_identification"
        - "topic_extraction"
      quality_thresholds:
        min_duration: 300  # 5 minutes
        max_duration: 7200  # 2 hours
        min_quality: 128  # kbps
      routing_rules:
        analysis_agent: "analysis_specialist"
        verification_agent: "verification_specialist"
        quality_agent: "quality_assurance_specialist"
    
    music:
      type: "audio"
      platform: "music"
      characteristics:
        - "creative"
        - "entertainment"
        - "copyright_sensitive"
        - "metadata_rich"
      processing_requirements:
        - "audio_analysis"
        - "metadata_extraction"
        - "copyright_check"
      quality_thresholds:
        min_duration: 30  # seconds
        max_duration: 600  # 10 minutes
        min_quality: 128  # kbps
      routing_rules:
        analysis_agent: "advanced_audio_analysis_specialist"
        verification_agent: "compliance_regulatory_officer"
        quality_agent: "quality_assurance_specialist"

  # Text Content Types
  text:
    article:
      type: "text"
      platform: "web"
      characteristics:
        - "long_form"
        - "informational"
        - "structured"
        - "citable"
      processing_requirements:
        - "text_analysis"
        - "fact_extraction"
        - "source_verification"
      quality_thresholds:
        min_length: 500  # characters
        max_length: 50000  # characters
        min_readability: 0.6
      routing_rules:
        analysis_agent: "analysis_specialist"
        verification_agent: "advanced_verification_specialist"
        quality_agent: "quality_assurance_specialist"
    
    social_post:
      type: "text"
      platform: "social"
      characteristics:
        - "short_form"
        - "conversational"
        - "trending"
        - "engagement_focused"
      processing_requirements:
        - "sentiment_analysis"
        - "trend_detection"
        - "engagement_prediction"
      quality_thresholds:
        min_length: 10  # characters
        max_length: 280  # characters
        min_engagement: 0.01
      routing_rules:
        analysis_agent: "enhanced_social_media_archivist"
        verification_agent: "advanced_verification_specialist"
        quality_agent: "quality_assurance_specialist"
    
    reddit_post:
      type: "text"
      platform: "reddit"
      characteristics:
        - "community_driven"
        - "discussion_focused"
        - "voting_system"
        - "subreddit_specific"
      processing_requirements:
        - "community_analysis"
        - "discussion_extraction"
        - "sentiment_analysis"
      quality_thresholds:
        min_length: 50  # characters
        max_length: 40000  # characters
        min_score: 0
      routing_rules:
        analysis_agent: "analysis_specialist"
        verification_agent: "verification_specialist"
        quality_agent: "quality_assurance_specialist"

  # Image Content Types
  image:
    photo:
      type: "image"
      platform: "social"
      characteristics:
        - "visual"
        - "shareable"
        - "metadata_rich"
        - "copyright_sensitive"
      processing_requirements:
        - "visual_analysis"
        - "object_detection"
        - "metadata_extraction"
      quality_thresholds:
        min_resolution: 640  # pixels
        max_resolution: 4096  # pixels
        min_quality: 0.7
      routing_rules:
        analysis_agent: "image_analysis_specialist"
        verification_agent: "advanced_verification_specialist"
        quality_agent: "quality_assurance_specialist"
    
    infographic:
      type: "image"
      platform: "web"
      characteristics:
        - "informational"
        - "data_visualization"
        - "educational"
        - "shareable"
      processing_requirements:
        - "text_extraction"
        - "data_analysis"
        - "fact_verification"
      quality_thresholds:
        min_resolution: 800  # pixels
        max_resolution: 4096  # pixels
        min_text_ratio: 0.1
      routing_rules:
        analysis_agent: "image_analysis_specialist"
        verification_agent: "advanced_verification_specialist"
        quality_agent: "quality_assurance_specialist"

  # Mixed Content Types
  mixed:
    livestream:
      type: "mixed"
      platform: "multiple"
      characteristics:
        - "real_time"
        - "interactive"
        - "multi_modal"
        - "ephemeral"
      processing_requirements:
        - "real_time_analysis"
        - "multi_modal_processing"
        - "interaction_analysis"
      quality_thresholds:
        min_duration: 60  # seconds
        max_duration: 28800  # 8 hours
        min_quality: 480  # pixels
      routing_rules:
        analysis_agent: "live_stream_analysis_specialist"
        verification_agent: "verification_specialist"
        quality_agent: "quality_assurance_specialist"
    
    thread:
      type: "mixed"
      platform: "social"
      characteristics:
        - "conversational"
        - "multi_post"
        - "narrative"
        - "context_dependent"
      processing_requirements:
        - "thread_reconstruction"
        - "narrative_analysis"
        - "context_extraction"
      quality_thresholds:
        min_posts: 2
        max_posts: 50
        min_engagement: 0.01
      routing_rules:
        analysis_agent: "enhanced_social_media_archivist"
        verification_agent: "advanced_verification_specialist"
        quality_agent: "quality_assurance_specialist"

# Content Processing Rules
processing_rules:
  # Priority levels for different content types
  priority_mapping:
    high_priority:
      - "livestream"
      - "breaking_news"
      - "viral_content"
    medium_priority:
      - "youtube"
      - "podcast"
      - "article"
    low_priority:
      - "social_post"
      - "photo"
      - "music"

  # Processing time limits (seconds)
  time_limits:
    real_time: 30
    fast: 300  # 5 minutes
    standard: 1800  # 30 minutes
    thorough: 3600  # 1 hour

  # Quality thresholds
  quality_thresholds:
    min_confidence: 0.7
    min_accuracy: 0.8
    max_processing_time: 3600
    min_content_quality: 0.6

# Routing Configuration
routing:
  # Default routing for unknown content types
  default_routing:
    analysis_agent: "analysis_specialist"
    verification_agent: "verification_specialist"
    quality_agent: "quality_assurance_specialist"
  
  # Fallback routing for failed processing
  fallback_routing:
    analysis_agent: "enhanced_analysis_specialist"
    verification_agent: "advanced_verification_specialist"
    quality_agent: "quality_assurance_specialist"
  
  # Emergency routing for critical content
  emergency_routing:
    analysis_agent: "mission_orchestrator"
    verification_agent: "executive_supervisor"
    quality_agent: "quality_assurance_specialist"

# Content Classification Rules
classification:
  # Automatic classification based on URL patterns
  url_patterns:
    youtube:
      - "youtube.com/watch"
      - "youtu.be/"
    tiktok:
      - "tiktok.com/"
      - "vm.tiktok.com/"
    twitter:
      - "twitter.com/"
      - "x.com/"
    reddit:
      - "reddit.com/"
    instagram:
      - "instagram.com/"
      - "instagr.am/"
  
  # Content type detection based on metadata
  metadata_detection:
    video_indicators:
      - "duration"
      - "video_codec"
      - "resolution"
    audio_indicators:
      - "audio_codec"
      - "sample_rate"
      - "channels"
    image_indicators:
      - "width"
      - "height"
      - "format"
    text_indicators:
      - "word_count"
      - "language"
      - "readability_score"

# Performance Optimization
performance:
  # Caching strategies for different content types
  caching:
    video:
      cache_duration: 3600  # 1 hour
      cache_size_limit: 1000  # items
    audio:
      cache_duration: 7200  # 2 hours
      cache_size_limit: 500  # items
    text:
      cache_duration: 1800  # 30 minutes
      cache_size_limit: 2000  # items
    image:
      cache_duration: 14400  # 4 hours
      cache_size_limit: 1000  # items
  
  # Processing optimization
  optimization:
    parallel_processing: true
    max_concurrent_tasks: 10
    batch_processing: true
    batch_size: 5
    retry_attempts: 3
    retry_delay: 5  # seconds
