# Deprecations Configuration
# TODO: Implement deprecation tracking and management

# Deprecation tracking
tracking:
  enabled: true
  log_level: "WARNING"
  # TODO: Add deprecation tracking configuration

# Deprecation policies
policies:
  grace_period_days: 30
  notification_frequency: "weekly"
  # TODO: Add deprecation policy configuration

# Deprecated features
features:
  # Example deprecated feature
  old_api:
    deprecated_since: "2024-01-01"
    removal_date: "2024-12-31"
    replacement: "new_api"
    # TODO: Add actual deprecated features

# Migration settings
migration:
  enabled: true
  auto_migrate: false
  # TODO: Add migration configuration

# Documentation settings
documentation:
  update_docs: true
  generate_reports: true
  # TODO: Add documentation update configuration
