# User Profiles Configuration
# TODO: Implement user profile and preference settings

# Profile settings
profiles:
  default:
    name: "Default Profile"
    preferences:
      language: "en"
      timezone: "UTC"
    # TODO: Add default profile configuration

# User preferences
preferences:
  notifications:
    enabled: true
    channels: ["discord", "email"]
    # TODO: Add notification preferences
  content_filtering:
    enabled: true
    categories: ["debate", "analysis"]
    # TODO: Add content filtering preferences
  privacy:
    data_sharing: false
    analytics: true
    # TODO: Add privacy preferences

# Profile management
management:
  auto_create: true
  migration_enabled: true
  # TODO: Add profile management configuration

# Customization settings
customization:
  themes:
    enabled: true
    default: "dark"
    # TODO: Add theme customization
  layouts:
    enabled: true
    default: "standard"
    # TODO: Add layout customization
