"""Helper modules for the Discord bot."""

from .analysis_renderer import (
    add_basic_video_info,
    add_completion_note,
    add_fallacies_field,
    add_fallback_content_summary,
    add_keywords_field,
    add_sentiment_field,
    add_summary_field,
    add_transcript_field,
    create_base_embed,
    extract_result_data,
)
from .tools_loader import (
    get_comprehensive_tool_specs,
    get_core_tool_specs,
    get_discord_tool_specs,
    get_tool_class,
    load_tools_from_specs,
    safe_instantiate,
)
from .ui_constants import (
    BALANCE_INDICATORS,
    BIAS_INDICATORS,
    BUTTON_STYLE_LINK,
    BUTTON_STYLE_PRIMARY,
    BUTTON_STYLE_SECONDARY,
    DEFAULT_FEATURE_FLAGS,
    DISCORD_MAX_CONTENT_LENGTH,
    DISCORD_TRUNCATION_SUFFIX,
    FACT_CHECKING_INDICATORS,
    LIGHTWEIGHT_IMPORT_FLAG,
    PATH_PRIORITY_SITE_PACKAGES,
    PATH_PRIORITY_SRC,
    PYTHON_VERSION,
    QUALITY_ACCEPTABLE_LENGTH_MAX,
    QUALITY_ACCEPTABLE_LENGTH_MIN,
    QUALITY_FULL_CREDIT_THRESHOLD,
    QUALITY_OPTIMAL_LENGTH_MAX,
    QUALITY_OPTIMAL_LENGTH_MIN,
    QUALITY_PARTIAL_CREDIT,
    QUALITY_PARTIAL_CREDIT_THRESHOLD,
    QUALITY_WEIGHT_BALANCE,
    QUALITY_WEIGHT_FACT_CHECKING,
    QUALITY_WEIGHT_LENGTH,
    QUALITY_WEIGHT_REASONING,
    REASONING_INDICATORS,
    SITE_PACKAGES_PATH,
)


__all__ = [
    # UI Constants
    "BALANCE_INDICATORS",
    "BIAS_INDICATORS",
    "BUTTON_STYLE_LINK",
    "BUTTON_STYLE_PRIMARY",
    "BUTTON_STYLE_SECONDARY",
    "DEFAULT_FEATURE_FLAGS",
    "DISCORD_MAX_CONTENT_LENGTH",
    "DISCORD_TRUNCATION_SUFFIX",
    "FACT_CHECKING_INDICATORS",
    "LIGHTWEIGHT_IMPORT_FLAG",
    "PATH_PRIORITY_SITE_PACKAGES",
    "PATH_PRIORITY_SRC",
    "PYTHON_VERSION",
    "QUALITY_ACCEPTABLE_LENGTH_MAX",
    "QUALITY_ACCEPTABLE_LENGTH_MIN",
    "QUALITY_FULL_CREDIT_THRESHOLD",
    "QUALITY_OPTIMAL_LENGTH_MAX",
    "QUALITY_OPTIMAL_LENGTH_MIN",
    "QUALITY_PARTIAL_CREDIT",
    "QUALITY_PARTIAL_CREDIT_THRESHOLD",
    "QUALITY_WEIGHT_BALANCE",
    "QUALITY_WEIGHT_FACT_CHECKING",
    "QUALITY_WEIGHT_LENGTH",
    "QUALITY_WEIGHT_REASONING",
    "REASONING_INDICATORS",
    "SITE_PACKAGES_PATH",
    # Analysis renderer functions
    "add_basic_video_info",
    "add_completion_note",
    "add_fallacies_field",
    "add_fallback_content_summary",
    "add_keywords_field",
    "add_sentiment_field",
    "add_summary_field",
    "add_transcript_field",
    "create_base_embed",
    "extract_result_data",
    # Tools loader functions
    "get_comprehensive_tool_specs",
    "get_core_tool_specs",
    "get_discord_tool_specs",
    "get_tool_class",
    "load_tools_from_specs",
    "safe_instantiate",
]
