"""Type stubs for scipy library."""

from typing import Any

# Basic scipy imports
stats: Any = ...
optimize: Any = ...
signal: Any = ...
linalg: Any = ...
spatial: Any = ...
interpolate: Any = ...

# Common scipy functions
def norm(x: Any, ord: int | None = None, axis: int | None = None) -> Any: ...
def solve(a: Any, b: Any) -> Any: ...
def inv(a: Any) -> Any: ...
def det(a: Any) -> Any: ...
def eig(a: Any) -> Any: ...
def svd(a: Any) -> Any: ...

# Stats functions
def pearsonr(x: Any, y: Any) -> Any: ...
def spearmanr(x: Any, y: Any) -> Any: ...
def kendalltau(x: Any, y: Any) -> Any: ...

# Optimization functions
def minimize(fun: Any, x0: Any, method: str = "BFGS", **kwargs: Any) -> Any: ...
def minimize_scalar(fun: Any, method: str = "brent", **kwargs: Any) -> Any: ...

# Signal processing
def butter(N: int, Wn: Any, btype: str = "low", analog: bool = False) -> Any: ...
def filtfilt(b: Any, a: Any, x: Any) -> Any: ...

# Interpolation
def interp1d(x: Any, y: Any, kind: str = "linear", **kwargs: Any) -> Any: ...
def griddata(points: Any, values: Any, xi: Any, method: str = "linear") -> Any: ...
