#!/usr/bin/env bash
set -euo pipefail

# Installs a lightweight pre-commit hook that blocks commits when deprecation
# violations are detected. Run from repo root:
#   bash scripts/install_deprecation_hook.sh
# To remove, delete .git/hooks/pre-commit or re-run `pre-commit install`.

HOOK_FILE=".git/hooks/pre-commit"

if [[ ! -d .git ]]; then
  echo "This script must be run from the repository root (no .git directory found)" >&2
  exit 1
fi

python_bin="${PYTHON:=python}"

cat > "$HOOK_FILE" <<'EOF'
#!/usr/bin/env bash
# Auto-generated by scripts/install_deprecation_hook.sh
set -euo pipefail

# Allow skipping (e.g., emergency hotfix) with SKIP_DEPRECATION_HOOK=1
if [[ "${SKIP_DEPRECATION_HOOK:-}" == "1" ]]; then
  echo "[deprecations] Skipped by SKIP_DEPRECATION_HOOK"
  exit 0
fi

python scripts/check_deprecations.py > /dev/null || {
  code=$?
  echo "[deprecations] Violations detected (exit=$code). Run: python scripts/check_deprecations.py" >&2
  exit $code
}

exit 0
EOF

chmod +x "$HOOK_FILE"
echo "Pre-commit deprecation hook installed at $HOOK_FILE"
