# Type stubs for opentelemetry.context
from typing import Any, TypeVar

T = TypeVar("T")

class Context(dict[str, Any]):
    """OpenTelemetry context dictionary."""
    def __init__(self) -> None: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def __getitem__(self, key: str) -> Any: ...

def get_current() -> Context: ...
def attach(context: Context) -> Any: ...
def detach(token: Any) -> None: ...

__all__ = ["Context", "attach", "detach", "get_current"]
