name: ci-a2a

on:
  pull_request:
    paths:
      - 'src/server/**'
      - 'src/client/**'
      - 'tests/test_a2a_*'
      - 'docs/a2a_*'
      - '.github/workflows/ci-a2a.yml'
  push:
    branches: [ main, master ]

jobs:
  a2a:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[dev]

      - name: Run A2A tests
        run: |
          make test-a2a

      - name: Upload A2A tools (collections)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: a2a-collections
          path: |
            docs/a2a_postman_collection.json
            docs/a2a_insomnia_collection.json
