name: MCP Import Safety Smoke

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  mcp-smoke:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: pyproject.toml

      - name: Install pytest only
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run MCP import-safety test
        env:
          PYTHONPATH: src
        run: |
          python -m pytest -q -c config/pytest.ini tests/test_mcp_imports.py
